# Generated by Django 4.0.3 on 2022-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_profiles',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
